# Generated by Django 6.0.4 on 2026-05-08 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BUDGET_ALERT', 'Budget Alert'), ('BUDGET_EXCEEDED', 'Budget Exceeded'), ('GOAL_COMPLETE', 'Goal Complete'), ('GOAL_PROGRESS', 'Goal Progress'), ('SEND_MONEY', 'Send Money'), ('DEPOSIT', 'Deposit'), ('GENERAL', 'General')], default='GENERAL', max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
