# Generated by Django 6.0.4 on 2026-04-26 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_budget_spended'),
        ('user', '0003_alter_wallet_total_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SavingGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deadline', models.DateField()),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_goals', to='user.wallet')),
            ],
        ),
    ]
