# Generated by Django 6.0.4 on 2026-04-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_savinggoals_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savinggoals',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In_progress'), ('complete', 'Complete')], default='in_progress', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('saving', 'Saving')], max_length=10),
        ),
    ]
