# Generated by Django 6.0.4 on 2026-04-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_savinggoals_status_alter_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
    ]
