# Generated by Django 6.0.4 on 2026-04-30 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='saving_goals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.savinggoals'),
        ),
    ]
