# Generated by Django 6.0.4 on 2026-05-02 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transaction_saving_goals'),
        ('user', '0003_alter_wallet_total_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reciever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('saving', 'Saving'), ('send', 'Sending')], max_length=10),
        ),
    ]
