# Generated by Django 6.0.4 on 2026-05-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_wallet_total_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='send_limit',
            field=models.PositiveBigIntegerField(default=3),
        ),
    ]
