# Generated by Django 6.0.3 on 2026-04-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('send', 'Send'), ('request', 'Request'), ('receive', 'Receive'), ('Deposit', 'Deposit')], max_length=20),
        ),
    ]
