# Generated by Django 6.0.4 on 2026-05-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
