# Generated by Django 6.0.4 on 2026-05-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_budget_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('completed', 'Completed')], default='active', max_length=255),
        ),
        migrations.AlterField(
            model_name='savinggoals',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In_progress'), ('complete', 'Complete'), ('failed', 'Failed')], default='in_progress', max_length=255),
        ),
    ]
