# Generated by Django 6.0.4 on 2026-04-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_budget_percentage_savinggoals'),
    ]

    operations = [
        migrations.AddField(
            model_name='savinggoals',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In_progress'), ('complete', 'Complete')], default='In_progress', max_length=255),
        ),
    ]
