# Generated by Django 6.0.4 on 2026-05-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_budget_status_alter_savinggoals_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='savinggoals',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savinggoals',
            name='remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
