# Generated by Django 6.0.4 on 2026-05-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_savinggoals_progress_savinggoals_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='savinggoals',
            name='percentage',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
