# Generated by Django 6.0.4 on 2026-05-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_transaction_reciever_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sending_limit',
            field=models.PositiveBigIntegerField(default=3),
        ),
    ]
