# Generated by Django 6.0.4 on 2026-05-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_transaction_sending_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='sending_limit',
        ),
    ]
