# Generated by Django 6.0.3 on 2026-04-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monthly_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saving_goals', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
