# Generated by Django 6.0.3 on 2026-04-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet_user',
            name='monthly_spending',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
