# Generated by Django 6.0.3 on 2026-04-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_wallet_user_monthly_spending'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet_user',
            name='last_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
