# Generated by Django 6.0.3 on 2026-04-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_wallet_user_last_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet_user',
            name='currently_month',
            field=models.IntegerField(default=0),
        ),
    ]
