# Generated by Django 6.0.3 on 2026-04-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_wallet_user_currently_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet_user',
            name='currently_year',
            field=models.IntegerField(default=0),
        ),
    ]
