# Generated by Django 6.0.4 on 2026-04-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_wallet_user_currently_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet_user',
            name='total_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wallet_user',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
